- name: Mount EFS volume
  ansible.builtin.mount:
    path: /var/www/html
    src: "{{ efs_id }}"
    fstype: efs
    opts: "tls,accesspoint={{ efs_ap_id }}"
    state: mounted

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted

- name: Install Log Agent
  ansible.builtin.dnf:
    name:
      - amazon-cloudwatch-agent
    state: present
    update_cache: true

- name: Create config for Log Agent
  ansible.builtin.template:
    src: config.json.j2
    dest: /opt/aws/amazon-cloudwatch-agent/bin/config.json
    mode: '0644'

- name: Start CloudWatch Agent with custom config
  ansible.builtin.command: >
    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl
    -a fetch-config
    -m ec2
    -c file:/opt/aws/amazon-cloudwatch-agent/bin/config.json
    -s
