- name: Install Python3 and python3-pip on Amazon Linux 2023
  ansible.builtin.dnf:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: true

- name: Install PyMySQL via pip3
  ansible.builtin.pip:
    name: PyMySQL
    executable: pip3

- name: Check connection to MySQL and database
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_host: "{{ db_endpoint }}"

- name: Create MySQL user 'wordpress' with password and grant privileges
  community.mysql.mysql_user:
    name: wordpress
    password: "wordpress@pass"
    priv: "wordpress.*:ALL"
    state: present
    login_user: "{{ mysql_user }}"
    login_password: "{{ mysql_password }}"
    login_host: "{{ db_endpoint }}"

- name: Restart httpd
  ansible.builtin.service:
    name: httpd
    state: restarted
